[package]
name = "veil-codec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_cbor.workspace = true
thiserror.workspace = true
veil-core = { path = "../veil-core" }
